### ISSUE TITLE
[bug] Invalid/empty 2.5.7 release

### ISSUE THREAD

**Issue by toteto** [WalletConnect/modal#16]
### Link to minimal reproducible example

/

### Summary

The latest release of 2.5.7 doesn't contain any code, causing failure at the connection with error `Module not found: Error: Can't resolve '@walletconnect/modal'` even though it is listed both both in package.json, yarn.lock and also present in node_modules/@walletconnect.

Temporary solution. using 2.5.6

### List of related npm package versions

@walletconnect/ethereum-provider 2.8.5

**Comment by 0xAsimetriq** [comment]
Apologies, something broke during build of `2.5.7`, it's been deprecated in favour of `2.5.8` now

**Comment by toteto** [comment]
Thanks for the fast response @0xAsimetriq 🙌
