### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by fulldecent** [WalletConnect/modal#27]
### Summary

![Screenshot 2023-09-02 at 18 22 24](https://github.com/WalletConnect/modal/assets/382183/a6c5c408-9688-4e2c-b13f-23e14e32c73e)

### Link to the related docs page

a

**Comment by SilentRhetoric** [comment]
Hi, can you please fix this?  At the rate the WC packages and docs have been changing and breaking, it is virtually impossible for anyone to integrate your technology.

**Comment by fulldecent** [comment]
It took me about 10 hours to study the WC documentation (which includes the actual documentation, the example, and then everything else everywhere on GitHub).

End result is about 20 lines of code. Including hacks and workarounds.

If you like you can check it out at TenThousandSu.com, read the source. I am only doing the CDN version.
